export const CREATE_BENEFICIARY = "CREATE_BENEFICIARY";
export const RETRIEVE_BENEFICIARY = "RETRIEVE_BENEFICIARY";
export const UPDATE_BENEFICIARY = "UPDATE_BENEFICIARY";
export const DELETE_BENEFICIARY = "DELETE_BENEFICIARY";
export const DELETE_ALL_BENEFICIARY = "DELETE_ALL_BENEFICIARY";